/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_linguofeng_jnitest_JNI */

#ifndef _Included_com_linguofeng_jnitest_JNI
#define _Included_com_linguofeng_jnitest_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_linguofeng_jnitest_JNI
 * Method:    echo
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_linguofeng_jnitest_JNI_echo
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_linguofeng_jnitest_JNI
 * Method:    add
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_linguofeng_jnitest_JNI_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
